### ISSUE TITLE
Latest release wont run

### ISSUE THREAD

**Issue by justinesmithies** [PhieF/CarnetElectron#10]
Just download the latest electron app and updated my android and NextCloud server. The Android and NextCloud sync ok but the Linux desktop app just sits at the logo page. I even tried deleting the Carnet folder from .Config and re entering the setup but it just does the same freezes.
Screenshot included.
![screenshot from 2018-12-04 19-35-00](https://user-images.githubusercontent.com/1571498/49468233-3a7eae00-f7fc-11e8-932b-e69962491780.png)

**Comment by justinesmithies** [comment]
If I run Carnet Electron from the terminal this is the output.

app uid 36d4fc64-56ba-b855
Documents/QuickNote
app uid 36d4fc64-56ba-b855
{ Error: Invalid response: 405 Method Not Allowed
    at handleResponseCode (/tmp/.mount_currenH6zB9x/resources/app.asar/node_modules/webdav/dist/response.js:7:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7) status: 405 }
found 13
path /home/justine/QuickNote
path /home/justine/QuickNote
path /home/justine/QuickNote
path /home/justine/QuickNote
path /home/justine/QuickNote
path /home/justine/QuickNote
path /home/justine/QuickNote
path /home/justine/QuickNote
/recentdb
path /home/justine/QuickNote
RecentDBManager with /home/justine/QuickNote/quickdoc/recentdb/36d4fc64-56ba-b855
getFullDB
/keywordsdb
path /home/justine/QuickNote
getFullDB
/recentdb/merge
/keywordsdb/merge
/settings/browser_css
/metadata?paths=Overtime.sqd%2C%2FHair%20Dye.sqd%2CHP%20Printer.sqd%2C
path /home/justine/QuickNote
this.note.path  /home/justine/QuickNote/HP Printer.sqd
path /home/justine/QuickNote
this.note.path  /home/justine/QuickNote//Hair Dye.sqd
path /home/justine/QuickNote
this.note.path  /home/justine/QuickNote/Overtime.sqd
path /home/justine/QuickNote
path /home/justine/QuickNote
path /home/justine/QuickNote
path /home/justine/QuickNote
path /home/justine/QuickNote
path /home/justine/QuickNote
quickdoc
Wines.sqd
nothing to do !
Overtime.sqd
nothing to do !
Hair Dye.sqd
nothing to do !
HP Printer.sqd
nothing to do !
quickdoc/recentdb
quickdoc/keywords
quickdoc/recentdb/recentnc
nothing to do !
quickdoc/recentdb/36d4fc64-56ba-b855
nothing to do !
quickdoc/recentdb/3626035c-c590-48ab-8793-835d2cd68fac
nothing to do !
quickdoc/keywords/keywordsnc
nothing to do !
quickdoc/keywords/36d4fc64-56ba-b855
nothing to do !
quickdoc/keywords/3626035c-c590-48ab-8793-835d2cd68fac
nothing to do !
local ends
exit, setting sync to 10 minutes
hasDownloadedSmt false
/settings/isfirstrun
/settings/current_version
path /home/justine/QuickNote
path /home/justine/QuickNote
RecentDBManager with /home/justine/QuickNote/quickdoc/recentdb//36d4fc64-56ba-b855
merging with /home/justine/QuickNote/quickdoc/recentdb//3626035c-c590-48ab-8793-835d2cd68fac
merging with /home/justine/QuickNote/quickdoc/keywords//3626035c-c590-48ab-8793-835d2cd68fac
getFullDB
undefined
getFullDB
RecentDBManager with /home/justine/QuickNote/quickdoc/recentdb//3626035c-c590-48ab-8793-835d2cd68fac
getFullDB
getFullDB
lock er undefined
RecentDBManager with /home/justine/QuickNote/quickdoc/recentdb//36d4fc64-56ba-b855
merging with /home/justine/QuickNote/quickdoc/recentdb//36d4fc64-56ba-b855
merging with /home/justine/QuickNote/quickdoc/keywords//36d4fc64-56ba-b855
getFullDB
undefined
getFullDB
RecentDBManager with /home/justine/QuickNote/quickdoc/recentdb//36d4fc64-56ba-b855
getFullDB
getFullDB
lock er undefined
RecentDBManager with /home/justine/QuickNote/quickdoc/recentdb//36d4fc64-56ba-b855
merging with /home/justine/QuickNote/quickdoc/recentdb//recentnc
merging with /home/justine/QuickNote/quickdoc/keywords//keywordsnc
getFullDB
undefined
getFullDB
RecentDBManager with /home/justine/QuickNote/quickdoc/recentdb//recentnc
getFullDB
getFullDB
lock er undefined
RecentDBManager with /home/justine/QuickNote/quickdoc/recentdb//36d4fc64-56ba-b855
merge finished has changed ? false
merge finished has changed ? false
/recentdb
path /home/justine/QuickNote
RecentDBManager with /home/justine/QuickNote/quickdoc/recentdb/36d4fc64-56ba-b855
getFullDB
/recentdb
path /home/justine/QuickNote
RecentDBManager with /home/justine/QuickNote/quickdoc/recentdb/36d4fc64-56ba-b855
getFullDB
/recentdb
path /home/justine/QuickNote
RecentDBManager with /home/justine/QuickNote/quickdoc/recentdb/36d4fc64-56ba-b855
getFullDB
/recentdb
path /home/justine/QuickNote
RecentDBManager with /home/justine/QuickNote/quickdoc/recentdb/36d4fc64-56ba-b855
getFullDB
/recentdb
path /home/justine/QuickNote
RecentDBManager with /home/justine/QuickNote/quickdoc/recentdb/36d4fc64-56ba-b855
getFullDB
